import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
   safe: {
      flex: 1,
      backgroundColor: "#f8fafc",
   },
   container: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 14,
   },
   header: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
      gap: 12,
   },
   backButton: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "#e2e8f0",
   },
   headerTextBox: {
      flex: 1,
   },
   title: {
      fontSize: 28,
      fontWeight: "900",
      color: "#0f172a",
   },
   subtitle: {
      marginTop: 3,
      fontSize: 14,
      fontWeight: "800",
      color: "#64748b",
   },
   scrollContent: {
      paddingBottom: 30,
   },
   form: {
      backgroundColor: "#fff",
      borderRadius: 22,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "#e2e8f0",
   },
   inputBox: {
      height: 54,
      borderRadius: 16,
      backgroundColor: "#f8fafc",
      borderWidth: 1,
      borderColor: "#e2e8f0",
      paddingHorizontal: 14,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
   },
   input: {
      flex: 1,
      fontSize: 15,
      fontWeight: "700",
      color: "#0f172a",
   },
   saveButton: {
      height: 54,
      borderRadius: 18,
      backgroundColor: "#2563eb",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
   },
   saveButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "900",
   },
   cancelButton: {
      height: 50,
      borderRadius: 16,
      backgroundColor: "#64748b",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
   },
   cancelButtonText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "900",
   },
   loadingBox: {
      paddingVertical: 30,
   },
   emptyText: {
      fontSize: 14,
      fontWeight: "800",
      color: "#64748b",
      textAlign: "center",
      marginTop: 20,
   },
   table: {
      backgroundColor: "#fff",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: "#e2e8f0",
      overflow: "hidden",
   },
   tableHeader: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#0f172a",
      paddingVertical: 12,
      paddingHorizontal: 12,
   },
   tableHeaderTitle: {
      flex: 1,
      fontSize: 13,
      fontWeight: "900",
      color: "#fff",
   },
   tableHeaderAmount: {
      width: 86,
      fontSize: 13,
      fontWeight: "900",
      color: "#fff",
      textAlign: "right",
   },
   tableHeaderActions: {
      width: 82,
      fontSize: 13,
      fontWeight: "900",
      color: "#fff",
      textAlign: "right",
   },
   tableRow: {
      minHeight: 58,
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderTopWidth: 1,
      borderTopColor: "#e2e8f0",
      gap: 10,
   },
   expenseTitle: {
      flex: 1,
      fontSize: 14,
      fontWeight: "900",
      color: "#0f172a",
   },
   expenseAmount: {
      width: 76,
      fontSize: 14,
      fontWeight: "900",
      color: "#ef4444",
      textAlign: "right",
   },
   actionsRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      width: 82,
      gap: 8,
   },
   iconButton: {
      width: 34,
      height: 34,
      borderRadius: 12,
      backgroundColor: "#2563eb",
      alignItems: "center",
      justifyContent: "center",
   },
   deleteIconButton: {
      backgroundColor: "#ef4444",
   },
});
