import { Room } from "./sectorB";

export const sectorA: Room[] = [
   {
      id: 1,
      room: 401,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 2,
      room: 402,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 3,
      room: 403,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 4,
      room: 404,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 5,
      room: 405,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 6,
      room: 406,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 7,
      room: 301,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 8,
      room: 302,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 9,
      room: 303,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 10,
      room: 304,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 11,
      room: 305,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 12,
      room: 306,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 13,
      room: 201,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 14,
      room: 202,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 15,
      room: 204,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 16,
      room: 205,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 17,
      room: 203,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 18,
      room: 206,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 19,
      room: 101,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 20,
      room: 102,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 21,
      room: 103,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 22,
      room: 104,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 23,
      room: 105,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 24,
      room: 106,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
];
