export type Room = {
   id: any;
   room: any;
   isFree: any;
   stayingTime: any;
   startTime: any;
   allPrice: any;
   onePrice: any;
   remainingAmount: any;
};

export const sectorB: Room[] = [
   {
      id: 1,
      room: 407,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 2,
      room: 408,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 3,
      room: 409,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 4,
      room: 4010,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 5,
      room: 4011,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 7,
      room: 307,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 8,
      room: 308,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 9,
      room: 309,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 10,
      room: 3010,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 11,
      room: 3011,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 13,
      room: 207,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 14,
      room: 208,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 15,
      room: 209,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 16,
      room: 2010,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 17,
      room: 2011,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 19,
      room: 107,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 20,
      room: 108,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },

   {
      id: 21,
      room: 109,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 22,
      room: 1010,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
   {
      id: 23,
      room: 1011,
      isFree: false,
      stayingTime: "",
      startTime: "",
      allPrice: "",
      onePrice: "",
      remainingAmount: "",
   },
];
